import type { Axis } from "@/types/ssd";
export type QuizAnswer={label:string;delta:Partial<Record<Axis,number>>}; export type QuizQuestion={prompt:string;answers:QuizAnswer[]};
export const quizQuestions:QuizQuestion[]=[
{prompt:"It’s 2:47 a.m. Why are you still awake?",answers:[{label:"Thinking about something I said in 2014.",delta:{melancholy:18,introspection:22,sociality:-12}},{label:"Excellent question. Next question.",delta:{absurdity:18,escape:12}},{label:"I’m working. Allegedly.",delta:{energy:12,introspection:10,absurdity:8}},{label:"Someone attractive made a terrible suggestion.",delta:{sensuality:22,sociality:18,energy:10}},{label:"The universe feels unusually suspicious tonight.",delta:{absurdity:22,cinematicity:16,escape:16}}]},
{prompt:"Choose an emergency object.",answers:[{label:"A bottle of whiskey with one glass left.",delta:{melancholy:15,introspection:12,sensuality:8}},{label:"A piano on fire.",delta:{energy:16,aggression:12,cinematicity:18}},{label:"A towel stolen from a questionable motel.",delta:{sensuality:12,absurdity:14,escape:10}},{label:"A toaster connected to Wi-Fi.",delta:{absurdity:22,introspection:6}},{label:"A white cat that clearly knows more than me.",delta:{absurdity:18,cinematicity:12,introspection:10}}]},
{prompt:"Your current emotional stability resembles:",answers:[{label:"Wet cardboard.",delta:{melancholy:20,energy:-14,introspection:14}},{label:"Reinforced concrete.",delta:{energy:14,aggression:8,melancholy:-10}},{label:"A casino chair at 5 a.m.",delta:{absurdity:18,energy:10,sociality:12}},{label:"A very expensive shoe with a broken heel.",delta:{sensuality:18,sociality:12,melancholy:8}},{label:"A Windows update stuck at 97%.",delta:{introspection:12,aggression:10,absurdity:15}}]},
{prompt:"You receive a text saying ‘we need to talk.’",answers:[{label:"Turn phone off.",delta:{escape:20,sociality:-16,introspection:10}},{label:"Turn music up.",delta:{energy:12,aggression:12,escape:10}},{label:"Reply ‘about what?’ immediately and regret it.",delta:{introspection:12,melancholy:10,sociality:10}},{label:"Go for a 10 km walk.",delta:{energy:18,escape:14,aggression:6}},{label:"Open wine. This is now an event.",delta:{sensuality:12,sociality:14,cinematicity:10}}]},
{prompt:"Pick tonight’s location.",answers:[{label:"Empty beach after sunset.",delta:{cinematicity:20,escape:16,melancholy:8}},{label:"Neon motel with terrible reviews.",delta:{sensuality:14,absurdity:14,cinematicity:12}},{label:"Cathedral during a thunderstorm.",delta:{cinematicity:22,introspection:14,aggression:8}},{label:"Gym basement with questionable ventilation.",delta:{energy:22,aggression:14,sensuality:-6}},{label:"Kitchen floor beside an open fridge.",delta:{absurdity:14,melancholy:10,introspection:12}}]},
{prompt:"What do you need from music right now?",answers:[{label:"Hold me together.",delta:{melancholy:20,introspection:18,energy:-10}},{label:"Break something safely.",delta:{aggression:24,energy:20}},{label:"Make me feel dangerous.",delta:{sensuality:18,aggression:12,energy:12}},{label:"Remove me from this planet temporarily.",delta:{escape:26,absurdity:14,cinematicity:14}},{label:"Make this ordinary walk unnecessarily cinematic.",delta:{cinematicity:26,escape:12}}]},
{prompt:"Pick a completely reasonable life strategy.",answers:[{label:"Think about it for another six months.",delta:{introspection:24,melancholy:8,energy:-8}},{label:"All in.",delta:{energy:20,aggression:10,sociality:8}},{label:"Leave without saying goodbye.",delta:{escape:22,sociality:-12,cinematicity:8}},{label:"Dance until the problem becomes tomorrow’s problem.",delta:{energy:20,sociality:20,absurdity:12}},{label:"Ask the toaster.",delta:{absurdity:28}}]},
{prompt:"Final question. How much damage are we dealing with?",answers:[{label:"Cosmetic.",delta:{energy:6}},{label:"Emotional but photogenic.",delta:{melancholy:12,cinematicity:16,sensuality:8}},{label:"Structurally concerning.",delta:{melancholy:14,aggression:10,introspection:12}},{label:"Mostly self-inflicted.",delta:{absurdity:12,aggression:8,introspection:10}},{label:"I clicked this because ‘playlist’ sounded safer than ‘therapy’.",delta:{absurdity:18,introspection:20,melancholy:10}}]}
];
export const neutralProfile:Record<Axis,number>={energy:50,melancholy:50,aggression:50,sensuality:50,absurdity:50,introspection:50,cinematicity:50,escape:50,sociality:50};
