import type { Axis } from "@/types/ssd";

export type QuizAnswer={label:string;delta:Partial<Record<Axis,number>>};
export type QuizQuestion={prompt:string;answers:QuizAnswer[];covers:Axis[]};

export const neutralProfile:Record<Axis,number>={energy:50,melancholy:50,aggression:50,sensuality:50,absurdity:50,introspection:50,cinematicity:50,escape:50,sociality:50};

export const quizQuestionPool:QuizQuestion[]=[
{prompt:"It’s 2:47 a.m. Why are you still awake?",covers:["melancholy","introspection","absurdity","escape","sensuality"],answers:[{label:"Thinking about something I said in 2014.",delta:{melancholy:18,introspection:22,sociality:-12}},{label:"Excellent question. Next question.",delta:{absurdity:18,escape:12}},{label:"I’m working. Allegedly.",delta:{energy:12,introspection:10,absurdity:8}},{label:"Someone attractive made a terrible suggestion.",delta:{sensuality:22,sociality:18,energy:10}},{label:"The universe feels unusually suspicious tonight.",delta:{absurdity:22,cinematicity:16,escape:16}}]},
{prompt:"Your phone rings. The caller ID is your own number.",covers:["introspection","escape","absurdity","aggression","sociality"],answers:[{label:"Answer. I’ve had worse ideas.",delta:{absurdity:18,energy:10}},{label:"Decline and block myself.",delta:{escape:20,absurdity:12,sociality:-8}},{label:"Let it ring and stare at it.",delta:{introspection:20,melancholy:8}},{label:"Answer aggressively.",delta:{aggression:20,energy:12}},{label:"Put it on speaker. Witnesses matter.",delta:{sociality:14,cinematicity:10,absurdity:8}}]},
{prompt:"A stranger at a bus stop whispers: ‘Don’t take the blue one.’ There are no buses.",covers:["absurdity","cinematicity","escape","introspection"],answers:[{label:"I ask about the red one.",delta:{absurdity:24,introspection:8}},{label:"I leave immediately.",delta:{escape:22,energy:8}},{label:"I wait. We’re committed now.",delta:{cinematicity:18,absurdity:14,introspection:8}},{label:"I nod like I already knew.",delta:{sociality:6,cinematicity:14}},{label:"I begin distrusting blue objects.",delta:{absurdity:18,introspection:12}}]},
{prompt:"You wake up in a very expensive hotel room. You did not book a hotel.",covers:["sensuality","escape","cinematicity","absurdity","sociality"],answers:[{label:"Check the minibar before asking questions.",delta:{sensuality:12,absurdity:10,energy:6}},{label:"Leave through the fire exit.",delta:{escape:24,energy:12}},{label:"Open the curtains dramatically.",delta:{cinematicity:22,sensuality:6}},{label:"Call reception and pretend this is normal.",delta:{sociality:14,absurdity:10}},{label:"Go back to sleep. Future me has resources.",delta:{escape:14,energy:-14,introspection:8}}]},
{prompt:"Choose one thing that absolutely should not be on fire.",covers:["aggression","cinematicity","absurdity","melancholy"],answers:[{label:"A wedding cake.",delta:{cinematicity:15,melancholy:10,absurdity:8}},{label:"A tax office.",delta:{aggression:22,energy:12,absurdity:8}},{label:"My left shoe.",delta:{absurdity:22,energy:6}},{label:"A piano in the rain.",delta:{cinematicity:24,melancholy:15}},{label:"Nothing. Fire needs boundaries.",delta:{introspection:12,aggression:-8}}]},
{prompt:"You have 20 minutes to leave the country. Pick one.",covers:["escape","sociality","cinematicity","introspection"],answers:[{label:"One suitcase.",delta:{escape:18,introspection:8}},{label:"One person.",delta:{sociality:22,melancholy:8}},{label:"One excellent lie.",delta:{cinematicity:18,absurdity:10}},{label:"No luggage. Better silhouette.",delta:{escape:22,cinematicity:12}},{label:"I need 21 minutes. Deal cancelled.",delta:{introspection:16,energy:-8}}]},
{prompt:"There is a horse in the lift. You are already late.",covers:["absurdity","energy","aggression","sociality"],answers:[{label:"Take the stairs. Horse wins.",delta:{energy:12,escape:8}},{label:"Get in. We’re colleagues now.",delta:{absurdity:20,sociality:12}},{label:"Ask which floor.",delta:{absurdity:24,sociality:8}},{label:"Press every button and create options.",delta:{absurdity:16,aggression:10,energy:10}},{label:"Go home. The day has made its position clear.",delta:{escape:20,energy:-12,melancholy:8}}]},
{prompt:"Someone offers you €10,000 to press a button marked ‘PROBABLY FINE’.",covers:["aggression","absurdity","energy","introspection"],answers:[{label:"Press it before they finish the sentence.",delta:{energy:22,aggression:12,absurdity:10}},{label:"Ask why ‘probably’ is in capitals.",delta:{introspection:22,absurdity:8}},{label:"Negotiate €15,000.",delta:{aggression:12,energy:12,sociality:8}},{label:"Press it with somebody else’s finger.",delta:{absurdity:22,sociality:-8}},{label:"Walk away and think about the €10,000 forever.",delta:{melancholy:12,introspection:18,energy:-10}}]},
{prompt:"You find a wedding ring inside a supermarket freezer.",covers:["melancholy","cinematicity","sensuality","absurdity","sociality"],answers:[{label:"Leave it. That story has enough characters.",delta:{introspection:14,melancholy:8}},{label:"Take it to customer service.",delta:{sociality:16,energy:4}},{label:"Try it on. Research purposes.",delta:{sensuality:14,absurdity:14}},{label:"Buy the frozen peas around it.",delta:{absurdity:20}},{label:"This is clearly the opening scene.",delta:{cinematicity:24,melancholy:8}}]},
{prompt:"A perfectly dressed stranger says: ‘Run.’ No explanation.",covers:["energy","escape","cinematicity","sensuality","aggression"],answers:[{label:"Run.",delta:{energy:24,escape:20}},{label:"Run, but in the same direction as them.",delta:{energy:18,sociality:10,cinematicity:12}},{label:"Ask ‘from what?’ like an amateur.",delta:{introspection:12,energy:-4}},{label:"Walk away slowly to establish dominance.",delta:{aggression:16,cinematicity:14}},{label:"Depends how attractive they are.",delta:{sensuality:22,absurdity:8}}]},
{prompt:"You are allowed one completely irresponsible purchase tonight.",covers:["sensuality","absurdity","energy","cinematicity"],answers:[{label:"A motorcycle I cannot ride.",delta:{energy:20,cinematicity:14,aggression:8}},{label:"A suit for an event that does not exist.",delta:{sensuality:14,cinematicity:16,absurdity:8}},{label:"A sword. No follow-up questions.",delta:{aggression:18,absurdity:16}},{label:"A one-way plane ticket.",delta:{escape:24,cinematicity:10}},{label:"Nothing. I already own the internet.",delta:{introspection:10,absurdity:12}}]},
{prompt:"The power goes out during dinner. Somebody starts laughing.",covers:["sociality","cinematicity","aggression","absurdity"],answers:[{label:"I laugh too. Better numbers.",delta:{sociality:18,absurdity:10}},{label:"I ask who touched what.",delta:{aggression:12,introspection:10}},{label:"Light candles. We have production value now.",delta:{cinematicity:22,sensuality:10}},{label:"Leave before Act II.",delta:{escape:18,sociality:-10}},{label:"Keep eating in total darkness.",delta:{absurdity:16,introspection:8}}]},
{prompt:"You discover a hidden door in your house that definitely wasn’t there yesterday.",covers:["escape","absurdity","cinematicity","introspection","energy"],answers:[{label:"Open it immediately.",delta:{energy:18,escape:14,absurdity:12}},{label:"Measure it first.",delta:{introspection:22,energy:-4}},{label:"Put a chair in front of it and move on.",delta:{escape:-8,introspection:10}},{label:"Invite someone over before opening it.",delta:{sociality:16,cinematicity:10}},{label:"Paint ‘DO NOT OPEN’ on it, then open it.",delta:{absurdity:22,cinematicity:14}}]},
{prompt:"A tattoo artist says: ‘Trust me, this version is funnier.’",covers:["absurdity","sociality","aggression","sensuality"],answers:[{label:"Fine. Commit to the bit.",delta:{absurdity:22,energy:10}},{label:"Absolutely not.",delta:{aggression:10,introspection:12}},{label:"How much funnier?",delta:{introspection:14,absurdity:8}},{label:"Only if nobody else has it.",delta:{sensuality:10,aggression:8}},{label:"I call a friend who makes worse decisions than me.",delta:{sociality:18,absurdity:10}}]},
{prompt:"Your ex sends ‘I had a weird dream about you.’",covers:["melancholy","sensuality","sociality","aggression","escape"],answers:[{label:"Delete without opening the sequel.",delta:{escape:18,sociality:-12}},{label:"‘How weird?’",delta:{sensuality:16,sociality:12}},{label:"Send a thumbs-up. Psychological warfare.",delta:{aggression:18,absurdity:10}},{label:"Read it twelve times and answer tomorrow.",delta:{melancholy:18,introspection:20}},{label:"‘Me too.’ This may be false.",delta:{cinematicity:12,sensuality:12,absurdity:8}}]},
{prompt:"You are handed a microphone in a room where nobody knows you.",covers:["sociality","energy","aggression","absurdity","melancholy"],answers:[{label:"Sing the chorus. No context.",delta:{energy:20,sociality:20,absurdity:10}},{label:"Say ‘this is a terrible idea’ and continue.",delta:{absurdity:16,sociality:12}},{label:"Give it back immediately.",delta:{sociality:-20,introspection:10}},{label:"Ask who is responsible for this.",delta:{aggression:12,sociality:6}},{label:"Dedicate something to someone who isn’t there.",delta:{melancholy:14,cinematicity:16}}]},
{prompt:"A fortune cookie says: ‘Not this time.’",covers:["absurdity","melancholy","introspection","aggression"],answers:[{label:"Fair.",delta:{melancholy:10,introspection:12}},{label:"Open another one. Appeal process.",delta:{energy:10,absurdity:18}},{label:"Take it personally.",delta:{melancholy:16,aggression:8}},{label:"Keep it in my wallet as evidence.",delta:{absurdity:16,introspection:12}},{label:"Eat the message too.",delta:{aggression:12,absurdity:20}}]},
{prompt:"You are at a funeral and somebody’s ringtone is ‘Stayin’ Alive’.",covers:["absurdity","sociality","melancholy","aggression"],answers:[{label:"Do not make eye contact with anyone.",delta:{sociality:-12,introspection:12,absurdity:8}},{label:"Leave the room before I laugh.",delta:{escape:14,absurdity:14}},{label:"This is objectively excellent timing.",delta:{absurdity:24}},{label:"Find the owner. I need to know them.",delta:{sociality:18,absurdity:12}},{label:"Somebody is getting punched later.",delta:{aggression:20,melancholy:6}}]},
{prompt:"You have to hide one object in your house before the police arrive. No context provided.",covers:["absurdity","energy","escape","introspection"],answers:[{label:"The toaster. It knows too much.",delta:{absurdity:24}},{label:"My phone.",delta:{escape:16,introspection:10}},{label:"Nothing. I want to know what I supposedly did.",delta:{aggression:12,introspection:16}},{label:"One completely innocent lamp.",delta:{absurdity:20,cinematicity:8}},{label:"Me.",delta:{escape:24,energy:12}}]},
{prompt:"You are offered immortality, but every Tuesday is mildly inconvenient forever.",covers:["absurdity","introspection","energy","melancholy"],answers:[{label:"Deal. Tuesdays already had a reputation.",delta:{energy:16,absurdity:14}},{label:"Define mildly.",delta:{introspection:22}},{label:"No. Eternity is poor scheduling.",delta:{introspection:18,melancholy:8}},{label:"Can I move Tuesday?",delta:{absurdity:18,sociality:4}},{label:"I accept and immediately regret the admin.",delta:{absurdity:12,melancholy:10,energy:8}}]},
{prompt:"The taxi driver says: ‘I know a faster way,’ then turns off the GPS.",covers:["escape","aggression","cinematicity","sociality","energy"],answers:[{label:"Excellent. Let the plot develop.",delta:{cinematicity:20,absurdity:10}},{label:"Turn my own GPS on silently.",delta:{introspection:14,energy:6}},{label:"Ask where we are going.",delta:{sociality:8,aggression:8}},{label:"Tell them to stop the car.",delta:{aggression:18,escape:14}},{label:"Send my location to three people.",delta:{sociality:14,introspection:10}}]},
{prompt:"At 3 a.m., someone knocks and says they have your missing shoe.",covers:["absurdity","cinematicity","sociality","escape"],answers:[{label:"I wasn’t missing a shoe.",delta:{introspection:14,absurdity:10}},{label:"Open the door. This deserves closure.",delta:{cinematicity:18,absurdity:16}},{label:"Ask them to leave it outside.",delta:{escape:12,sociality:-8}},{label:"Ask what colour it is.",delta:{absurdity:20,introspection:8}},{label:"Pretend not to be home. In my own home.",delta:{escape:20,absurdity:8}}]},
{prompt:"Choose a hill to die on, metaphorically please.",covers:["aggression","introspection","sociality","absurdity"],answers:[{label:"The playlist was better before everyone found it.",delta:{aggression:10,introspection:10}},{label:"Brunch is not a personality.",delta:{aggression:18,sociality:-8}},{label:"Nobody needs seven decorative pillows.",delta:{aggression:14,absurdity:8}},{label:"Reply-all should require a licence.",delta:{aggression:16,sociality:-10}},{label:"I reserve my rage for structurally important nonsense.",delta:{introspection:18,aggression:10}}]},
{prompt:"You are given one hour where consequences are temporarily unavailable.",covers:["energy","sensuality","escape","sociality","aggression","absurdity"],answers:[{label:"Book a flight and miss the return window.",delta:{escape:24,energy:14}},{label:"Call somebody I absolutely should not call.",delta:{sensuality:18,sociality:18,melancholy:8}},{label:"Break one expensive-looking object.",delta:{aggression:22,energy:16}},{label:"Sleep. Consequences can’t improve that offer.",delta:{energy:-20,escape:12}},{label:"Spend 45 minutes deciding.",delta:{introspection:22,absurdity:8}}]}
];

function shuffle<T>(items:T[]):T[]{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}

export function buildRandomQuiz(count=8):QuizQuestion[]{
  const allAxes=Object.keys(neutralProfile) as Axis[];
  for(let attempt=0;attempt<40;attempt++){
    const selection=shuffle(quizQuestionPool).slice(0,count);
    const covered=new Set(selection.flatMap((q)=>q.covers));
    if(allAxes.every((axis)=>covered.has(axis)))return selection;
  }
  return shuffle(quizQuestionPool).slice(0,count);
}
